In [ ]:
# Rakibul Islam
# 151-15-5131

In [89]:
import numpy as np

In [90]:
outlook = np.array([0, 0, 1, 0, 1, 1, 0]) 
#sunny = 0 , cloudy = 1
temperature = np.array ([0, 1, 1, 1, 0, 0, 0])
#cold = 0, warm = 1
routine = np.array([0, 1, 0, 0 ,0, 1, 1])
#indoor = 0, outdoor = 1
coat = np.array ([0, 0, 0, 0, 1, 1, 1])
#no = 0, yes = 1

In [91]:
x = (1, 1, 1)
# cloudy , warm , outdoor

In [92]:
# c = yes

a_1 = np.argwhere (coat == 1)
print (a_1)

[[4]
 [5]
 [6]]


In [93]:
b_1 = outlook[4:]
print (b_1)

[1 1 0]


In [94]:
c_1 = temperature [4:]
print (c_1)

[0 0 0]


In [95]:
d_1 = routine [4:]
print(d_1)

[0 1 1]


In [96]:
e_1 =np.argwhere(b_1==1)
print(e_1)

[[0]
 [1]]


In [97]:
f_1 =np.argwhere(c_1==1)
print(f_1)

[]


In [98]:
g_1=np.argwhere(d_1==1)
print(g_1)

[[1]
 [2]]


In [99]:
w_1 = ((len(e_1)/len(a_1))*(len(f_1)/len(a_1))*(len(g_1)/len(a_1))*(len(a_1)/len(coat)))
print(w_1)

0.0


In [100]:
h = np.argwhere(outlook==1)
print(h)

[[2]
 [4]
 [5]]


In [101]:
i = np.argwhere(temperature==1)
print(i)

[[1]
 [2]
 [3]]


In [102]:
j = np.argwhere(routine==1)
print(j)

[[1]
 [5]
 [6]]


In [103]:
v_1=(len(h)/len(outlook))*(len(i)/len(temperature))*(len(j)/len(routine))
print(v_1)

0.07871720116618075


In [104]:
z_1 = (w_1/v_1)
print (z_1)

0.0


In [105]:
#  c = no
a_0 = np.argwhere (coat == 0)
print (a_0)

[[0]
 [1]
 [2]
 [3]]


In [106]:
b_0 = outlook[:4]
print (b_0)

[0 0 1 0]


In [107]:
c_0 = temperature [:4]
print (c_0)

[0 1 1 1]


In [108]:
d_0 = routine [:4]
print(d_0)

[0 1 0 0]


In [109]:
e_0 =np.argwhere(b_0 ==1)
print(e_0)

[[2]]


In [110]:
f_0 =np.argwhere(c_0==1)
print(f_0)

[[1]
 [2]
 [3]]


In [111]:
g_0=np.argwhere(d_0==1)
print(g_0)

[[1]]


In [112]:
w_0 = ((len(e_0)/len(a_0))*(len(f_0)/len(a_0))*(len(g_0)/len(a_0))*(len(a_0)/len(coat)))
print(w_0)

0.026785714285714284


In [113]:
v_0=(len(h)/len(outlook))*(len(i)/len(temperature))*(len(j)/len(routine))
print(v_0)

0.07871720116618075


In [114]:
z_0 = (w_0/v_0)
print (z_0)

0.3402777777777778


In [115]:
# condition 
if (z_1<z_0):
    print ("no")
else :
    print("yes")

no
